### ISSUE TITLE
App: Custom payment

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-custom-payment#1]
- [x] Setup do repo (falta o token de parceiro do @matheusgnreis );
- [x] Configuração do app seguindo instruções em [next steps](https://github.com/ecomplus/app-custom-payment#next-steps);
- [x] Como é comum para formas de pagamento, precisaremos dos módulos `list_payments` e `create_transaction`, necessário implementar as corretamente as respectivas rotas em `functions/routes/ecom/modules/` (apesar de ser outra categoria de app, [Custom Shipping](https://github.com/ecomplus/app-custom-shipping/tree/master/routes/ecom/modules) pode servir de referência);
- [x] Descrição e um ícone legal (@vitorrgg )  pro Market (instruções [aqui](https://github.com/ecomplus/app-custom-payment#optional-setup-for-market));

**Comment by leomp12** [comment]
@thiagoabreudev esqueci de te falar, você vai precisar de uma conta de parceiro pra publicar o app depois: https://docs.google.com/forms/u/0/d/1L3B2yqQyMfdzzeXLyKqQHEx0wJ8utZWBw9Hv2WdQG9o/viewform?edit_requested=true

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-custom-payment/pull/4

**Comment by vitorrgg** [comment]
Segue o icone
![custom_payment](https://user-images.githubusercontent.com/35348281/78582776-31e12200-780c-11ea-90b7-096f275af225.png)

**Comment by leomp12** [comment]
Falta a descrição do app em md ainda, quem se habilita @vitorrgg @talissonf ?

Depois só configurar o token da sua conta e publicar pro market @talissonf (https://github.com/ecomplus/app-custom-payment#optional-setup-for-market), quando tiver tudo pronto dá um `npm run release`, isto vai gerar uma versão nova e triggar o publish pro market (assim espero, não testei isso)

**Comment by talissonf** [comment]
@leomp12  Eu não tenho permissão pra configurar variáveis no repositório.

**Comment by leomp12** [comment]
@talissonf verdade, vê se agora dá...

**Comment by talissonf** [comment]
@leomp12 ainda não.

**Comment by talissonf** [comment]
publicado https://market.e-com.plus/apps/custom-payment

**Comment by leomp12** [comment]
A descrição tá mixuruca ainda, mas deu tudo certin agora:
https://market.e-com.plus/apps/custom-payment
https://github.com/ecomplus/app-custom-payment/runs/568442426
