### ISSUE TITLE
Authenticação desnecessária

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-custom-payment#11]
Este app está usando autenticação com escopo pra criar procedures e ler dados da loja, mas não me parece necessário. A única coisa que ele faz (e não vejo outra possibilidade) é respoder os módulos list payments e create transaction, não precisamos autenticar na Store API pra isto.
Algum motivo pra isto @talissonf ?

**Comment by talissonf** [comment]
Não, eu deixei o que tava do starter

**Comment by leomp12** [comment]
Certo, fica aquilo no starter como exemplo mais comum, mas é bom revisar o scopo em cada app e se possível (neste caso por exemplo) nem usar autenticação nenhuma.
