### ISSUE TITLE
Adicionar 'filtro' por forma de envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-custom-payment#12]
Na configuração do app, permitir a inserção de uma determinada forma de envio, de modo que se for escolhido, no checkout só irá aparecer a forma de pagamento customizada, vide solicitação:
https://community.e-com.plus/t/pagamento-personalizado/270
Acredito que seja um issue para frete personalizado, porque pelo resultado que vi no json, as formas de pagamento têm IDs e na minha cabeça colocando o ID ao criar a forma de envio ficaria mais fácil, mas enfim, se tiver errado abro no outro

**Comment by leomp12** [comment]
> Teria como colocar uma configuração adicional para faixa de CEP?

Foi implementado por faixa de CEP a alguns dias e eu não tinha visto o issue, mas não por forma de envio...
Até onde eu entendi a solicitação era por faixa de CEP mesmo.

**Comment by matheusgnreis** [comment]
Está perfeito, tem que apagar o app e instalar de novo para pegar a nova versão, ou só configurar?

**Comment by leomp12** [comment]
Sim, até atomatizarmos a atualização do app sempre tem que instalar novamente (ou dar um PATCH no `admin_settings` via API)
