### ISSUE TITLE
Aplicando desconto entre regras diferentes

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-custom-payment#28]
Aparentemente quando um desconto é configurado para uma opção de pagamento no app ela acaba também sendo aplicada em outras opções de pagamento :open_mouth:
Na lista o desconto é retornado apenas em uma opção de pagamento mesmo (certo até aí), mas se selecionada a outra opção o desconto é aplicado:

![Screenshot_2020-12-07 My Shop](https://user-images.githubusercontent.com/10326572/101407753-1dcd5300-38ba-11eb-8feb-40a0e10053da.png)
![Screenshot_2020-12-07 My Shop(2)](https://user-images.githubusercontent.com/10326572/101407758-202fad00-38ba-11eb-9cc9-97cec7f5ef22.png)

**Comment by matheusgnreis** [comment]
Na loja LOV está diferente, não aplica desconto em nenhuma forma de pagamento customizada https://github.com/ecomplus/app-custom-payment/issues/30

![checkout](https://user-images.githubusercontent.com/35343551/101645078-b677e600-3a14-11eb-85da-6e9f00d073e6.PNG)
![desconto](https://user-images.githubusercontent.com/35343551/101644853-74e73b00-3a14-11eb-8d00-914aa452de8e.png)
![pix](https://user-images.githubusercontent.com/35343551/101644987-9cd69e80-3a14-11eb-8770-2cc2c8e4c5d0.png)

**Comment by leomp12** [comment]
@matheusgnreis possivelmente já tenha fixado isso, mas o @talissonf vai dar um release pra nós com mais uma alteração pra garantir :+1:

**Comment by talissonf** [comment]
@leomp12 @matheusgnreis ainda não dei release porque tava testando. 
Ta instalado na 1011 apontando pro meu local, se puderem testar novamente @ThaisChaves @matheusgnreis , alterem as formas de pagamento, altera o valor dos descontos, etc..
Se tiver ok libero o release.

**Comment by ThaisChaves** [comment]
@talissonf: Dá uma olhada aqui: O Deposito esta configurado em 60% de desconto NÃO cumulativo.
Ai coloquei o cupom que dá 20% de desconto. Ele tirou os 60% de desconto da forma de pagamento, mas na tela de finalização, mostrou um valor errado de 400,00.
Dá uma olhada no video:

https://drive.google.com/file/d/1qmCccapjKC_FYbGYJMRUUPHBtaonzDpC/view?usp=sharing

**Comment by talissonf** [comment]
@ThaisChaves se pude refazer o teste acho que fixei

**Comment by ThaisChaves** [comment]
Agora, coloquei a forma de pagamento com o desconto **cumulativo** ai deu o problema.

![Screenshot (19)](https://user-images.githubusercontent.com/60987858/101833025-240c3b00-3b17-11eb-8e03-1f2b260da57d.png)

(a situação anterior com **não cumulativou** ficou corrigida).

**Comment by talissonf** [comment]
@ThaisChaves arrumado

**Comment by ThaisChaves** [comment]
@leomp12  e @talissonf , preciso só que confirmem por favor: 
Agora esta mostrando na tela da finalização, a descrição do pagamento(eu ate acho melhor, pq ela trabalha com tags e não precisaria do cara repetir a informação em método do pagamento). Vai ficar a descrição mesmo? (só confirmando pq tem posts na comunidade sobre isso. 
* outro ponto é: Da pra tratar as tags html na tela da finalização tbm? Coloquei a imagem abaixo pra facilitar o entendimento:

![Screenshot (24)](https://user-images.githubusercontent.com/60987858/101904856-42188080-3b95-11eb-9c60-9df5c84ce445.png)

**Comment by ThaisChaves** [comment]
@talissonf: Mudou o valor da compra após finalizar a venda:

Para simular:
* Precisa ter valor de frete INCLUÍDO no carrinho (sem frete não deu o problema).
* desconto não cumulativo.
* Desconto na forma de pagamento esta aplicado ao TOTAL:
![Screenshot (25)](https://user-images.githubusercontent.com/60987858/101909039-bbb36d00-3b9b-11eb-9743-d8d398a2344a.png)

Abaixo o vídeo: Quando finalizou a compra, mudou o valor a pagar: 
https://drive.google.com/file/d/14ZsK2asxBV4vmyigTkut9cOmsdy4YOH3/view?usp=sharing

**Comment by talissonf** [comment]
@leomp12 isso pode ser o aplicativo de descontos? meu create_transaction não envia mais o valor do discount, só o amount.total e esse vindo do módulo.

**Comment by leomp12** [comment]
@talissonf não porque ele é aplicado antes de tudo na verdade...
Mas nesse pedido nem tem desconto por cupom, e nem deveria porque o cupom que a @ThaisChaves usou está com pedido mínimo de R$ 500,00 se não me engano, no JSON do pedido não há cupom e o desconto aplicado da forma de pagamento então está correto (não acumulou).
O valor na confirmação está certo, o problema aí pareceu ser no Storefront, talvez a @ThaisChaves aplicou esse cupom antes, mexeu no carrinho de alguma forma e ele permaneceu "aplicado", foi isso?

**Comment by leomp12** [comment]
> Agora esta mostrando na tela da finalização, a descrição do pagamento(eu ate acho melhor, pq ela trabalha com tags e não precisaria do cara repetir a informação em método do pagamento). Vai ficar a descrição mesmo? (só confirmando pq tem posts na comunidade sobre isso.

Sim, atendendo a este issue https://github.com/ecomplus/app-custom-payment/issues/29

> outro ponto é: Da pra tratar as tags html na tela da finalização tbm?

Sim, eu vi isso em um teste e já fiz, no próximo release do Storefront :+1:

**Comment by talissonf** [comment]
Vou liberar o release então.

**Comment by ThaisChaves** [comment]
@talissonf  e @leomp12 

Aqui: Não tem haver com cupom de desconto não.

**Se tem frete e a forma de pagamento tem desconto esta dando problema.**

Não tinha cupom de desconto no exemplo abaixo.

Olha esse aqui: forma de pagamento com desconto fixo de 10,00. Com frete o valor do desconto de 10,00 dobra quando fecha a venda:

https://drive.google.com/file/d/17EtqeOxfhTQ_AHK8z3LWzRHCjvYfVd3C/view?usp=sharing

**Comment by leomp12** [comment]
Então @ThaisChaves , na verdade no primeiro vídeo tinha um cupom no seu carrinho, e não deveria ter porque o cupom tem valor mínimo menor do que o montante do seu carrinho, no checkout isso foi verificado e o cupom foi ignorado, por isso o desconto da forma de pagamento foi aplicada, mesmo não sendo cumulativa, já que não havia desconto extra anterior. Tem um problema aí, mas não da forma de pagamento.

Nos dois vídeos de fato ele muda o valor do frete, não sei se ele está entrando em uma regra de frete grátis inconsistentemente ou se está de fato alterando a opção de envio selecionada (tem que verificar isso no pedido), de qualquer forma isso também não tem como ser um erro da forma de pagamento, pode ser um problema do Storefront, do módulo de checkout ou só algo de errado nas configurações do aplicativo da transportadora.

**Comment by talissonf** [comment]
@ThaisChaves eu desabilitei o app q tava apontado pro meu local, o que ficou habilitado é um que tava na 1011 e deve ta com outras configurações de desconto. Talvez seja isto!

**Comment by leomp12** [comment]
Mas independente disso o app de pagamento não tem como mudar a forma de envio, o frete mudar não tem como ser problema do app de pagamento, mas vale testar melhor pra identificar onde de fato é o problema e abrir o issue respectivo...
