### ISSUE TITLE
Sistema não considerou o desconto quando finalizou a compra

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-custom-payment#30]
Veja no video, que escolho a forma de pagamento com desconto. Ele mostra o valor do desconto correto. Quando finalizo a compra, muda o valor. 

https://drive.google.com/file/d/1P8_hAj17VUu6NLPSwa-sclM1V5LcKERr/view?usp=sharing

Teste feito utilizando a loja storefront-baby: https://storefront-baby.netlify.app/

usuário e senha do admin com Thaís ou Matheus. Configuração esta na loja 1117.

**Comment by leomp12** [comment]
Duplicado de #27
