### ISSUE TITLE
Parou de mostrar o valor do desconto do pagamento personalizado no card de produto

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-custom-payment#32]
Se o pagamento personalizado tem desconto, esse desconto mostrava no card do produto e também quando entrava nele e visualizava as formas de pagamento.

**Hoje só vejo que tem desconto na tela de finalização**.

Loja de exemplo: https://storefront-baby.netlify.app/
![Screenshot (40)](https://user-images.githubusercontent.com/60987858/102494197-1264ef00-4053-11eb-8ce3-f86ffb3de8a8.png)

Antes, no card do produto mostrava o valor com os 10% de desconto e também no produto (nas formas de pagamento  agora só tem o nome. Não mostra os 10% de desconto).

**Comment by leomp12** [comment]
@talissonf parece que no último fix parou de retornar o `discount_option` no GET do list payments...

**Comment by talissonf** [comment]
👍🏼

**Comment by leomp12** [comment]
@talissonf era só porque você passou a checar `amount.discount <= 0` e na verdade nessa situação ele é undefined.
Tá resolvido.
